/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Document on Azure Functions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Userlogin
 */
export interface Userlogin {
    /**
     * 
     * @type {string}
     * @memberof Userlogin
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof Userlogin
     */
    password?: string;
}

/**
 * Check if a given object implements the Userlogin interface.
 */
export function instanceOfUserlogin(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserloginFromJSON(json: any): Userlogin {
    return UserloginFromJSONTyped(json, false);
}

export function UserloginFromJSONTyped(json: any, ignoreDiscriminator: boolean): Userlogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserloginToJSON(value?: Userlogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'password': value.password,
    };
}

