/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificationsAndLicense
 */
export interface CertificationsAndLicense {
    /**
     * 
     * @type {string}
     * @memberof CertificationsAndLicense
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationsAndLicense
     */
    issuedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationsAndLicense
     */
    issueDate?: string;
}

/**
 * Check if a given object implements the CertificationsAndLicense interface.
 */
export function instanceOfCertificationsAndLicense(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CertificationsAndLicenseFromJSON(json: any): CertificationsAndLicense {
    return CertificationsAndLicenseFromJSONTyped(json, false);
}

export function CertificationsAndLicenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificationsAndLicense {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'issuedBy': !exists(json, 'issuedBy') ? undefined : json['issuedBy'],
        'issueDate': !exists(json, 'issueDate') ? undefined : json['issueDate'],
    };
}

export function CertificationsAndLicenseToJSON(value?: CertificationsAndLicense | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'issuedBy': value.issuedBy,
        'issueDate': value.issueDate,
    };
}

