/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reference
 */
export interface Reference {
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    jobTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    companyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    phoneNumber?: string;
}

/**
 * Check if a given object implements the Reference interface.
 */
export function instanceOfReference(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceFromJSON(json: any): Reference {
    return ReferenceFromJSONTyped(json, false);
}

export function ReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'jobTitle': !exists(json, 'jobTitle') ? undefined : json['jobTitle'],
        'companyName': !exists(json, 'companyName') ? undefined : json['companyName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function ReferenceToJSON(value?: Reference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'jobTitle': value.jobTitle,
        'companyName': value.companyName,
        'email': value.email,
        'phoneNumber': value.phoneNumber,
    };
}

