/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContactInformation } from './ContactInformation';
import {
    ContactInformationFromJSON,
    ContactInformationFromJSONTyped,
    ContactInformationToJSON,
} from './ContactInformation';

/**
 * 
 * @export
 * @interface PersonalInformation
 */
export interface PersonalInformation {
    /**
     * 
     * @type {string}
     * @memberof PersonalInformation
     */
    name?: string;
    /**
     * 
     * @type {ContactInformation}
     * @memberof PersonalInformation
     */
    contactInformation?: ContactInformation;
}

/**
 * Check if a given object implements the PersonalInformation interface.
 */
export function instanceOfPersonalInformation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PersonalInformationFromJSON(json: any): PersonalInformation {
    return PersonalInformationFromJSONTyped(json, false);
}

export function PersonalInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'contactInformation': !exists(json, 'contactInformation') ? undefined : ContactInformationFromJSON(json['contactInformation']),
    };
}

export function PersonalInformationToJSON(value?: PersonalInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'contactInformation': ContactInformationToJSON(value.contactInformation),
    };
}

