/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Education
 */
export interface Education {
    /**
     * 
     * @type {string}
     * @memberof Education
     */
    schoolName?: string;
    /**
     * 
     * @type {string}
     * @memberof Education
     */
    degreeType?: string;
    /**
     * 
     * @type {string}
     * @memberof Education
     */
    major?: string;
    /**
     * 
     * @type {string}
     * @memberof Education
     */
    graduationDate?: string;
    /**
     * 
     * @type {string}
     * @memberof Education
     */
    gpa?: string;
}

/**
 * Check if a given object implements the Education interface.
 */
export function instanceOfEducation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EducationFromJSON(json: any): Education {
    return EducationFromJSONTyped(json, false);
}

export function EducationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Education {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schoolName': !exists(json, 'schoolName') ? undefined : json['schoolName'],
        'degreeType': !exists(json, 'degreeType') ? undefined : json['degreeType'],
        'major': !exists(json, 'major') ? undefined : json['major'],
        'graduationDate': !exists(json, 'graduationDate') ? undefined : json['graduationDate'],
        'gpa': !exists(json, 'gpa') ? undefined : json['gpa'],
    };
}

export function EducationToJSON(value?: Education | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schoolName': value.schoolName,
        'degreeType': value.degreeType,
        'major': value.major,
        'graduationDate': value.graduationDate,
        'gpa': value.gpa,
    };
}

