/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CandidateDto
 */
export interface CandidateDto {
    /**
     * 
     * @type {string}
     * @memberof CandidateDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateDto
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateDto
     */
    dob?: string;
}

/**
 * Check if a given object implements the CandidateDto interface.
 */
export function instanceOfCandidateDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CandidateDtoFromJSON(json: any): CandidateDto {
    return CandidateDtoFromJSONTyped(json, false);
}

export function CandidateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandidateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'dob': !exists(json, 'dob') ? undefined : json['dob'],
    };
}

export function CandidateDtoToJSON(value?: CandidateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
        'email': value.email,
        'phone': value.phone,
        'gender': value.gender,
        'dob': value.dob,
    };
}

