/* tslint:disable */
/* eslint-disable */
/**
 * CCubAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tenant
 */
export interface Tenant {
    /**
     * 
     * @type {number}
     * @memberof Tenant
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Tenant
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Tenant
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Tenant
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Tenant
     */
    emailId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Tenant
     */
    contact?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Tenant
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Tenant
     */
    updatedDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Tenant
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the Tenant interface.
 */
export function instanceOfTenant(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TenantFromJSON(json: any): Tenant {
    return TenantFromJSONTyped(json, false);
}

export function TenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tenant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'emailId': !exists(json, 'emailId') ? undefined : json['emailId'],
        'contact': !exists(json, 'contact') ? undefined : json['contact'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'updatedDate': !exists(json, 'updatedDate') ? undefined : (json['updatedDate'] === null ? null : new Date(json['updatedDate'])),
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
    };
}

export function TenantToJSON(value?: Tenant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'url': value.url,
        'emailId': value.emailId,
        'contact': value.contact,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
        'updatedDate': value.updatedDate === undefined ? undefined : (value.updatedDate === null ? null : value.updatedDate.toISOString()),
        'isActive': value.isActive,
    };
}

