name: API-build & deploy
on:
  push:
    branches:      
      - main
    paths:
      - 'candidate/**'
      - '.github/workflows/api-candidate.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './candidate'
  JAVA_VERSION: '11'

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3.5.3

      - name: 'Set up Java ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'

      - name: 'Build Java App with Maven'
        run: mvn clean package
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: 'Run Azure Functions Action'
        uses: azure/functions-action@v1
        with:
          app-name: 'api-candidate-dev-001' # Replace with your Azure Function App name
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/build/libs/candidate.jar' # Update with the correct path to the JAR file
          publish-profile: ${{ secrets.API_PUBLISH_PROFILE }} # Replace with the name of your secret containing the .publishsettings content
