name: microsite-api-build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/apis/microsite/**'
      - '.github/workflows/api-microsite.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/apis/microsite/'
  DOTNET_VERSION: '6.0.x'
  AZURE_APP_WORKING_DIR: './src/apis/microsite/'
  VITE_STRG_ACCOUNT_KEY: ${{ secrets.VITE_STRG_ACCOUNT_KEY }}

jobs:
  api-microsite-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest  
    environment: Development

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2  

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2  
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Using .NET
        run: dotnet publish -c Release --output ./output -r win-x86 -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true
        working-directory: ${{ env.AZURE_APP_WORKING_DIR }}

      - name: Test with the dotnet CLI
        run: dotnet test
        working-directory: ${{ env.AZURE_APP_WORKING_DIR }}

      - name: Run Azure Functions Action
        id: fa
        uses: Azure/functions-action@v1
        with:
          app-name: 'api-ccmicrosite-dev-001'
          package: ${{ env.AZURE_APP_WORKING_DIR }}output
          publish-profile: ${{ secrets.API_MICROSITE_PUBLISH_PROFILE }}
