name: content-api-build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/apis/ContentManagement/**'
      - '.github/workflows/api-content.yml'
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_APP_WORKING_DIR: './src/apis/ContentManagement/'

jobs:
  api-content-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest  
    environment: Development

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2  

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2  
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Using .NET
        run: dotnet publish -c Release --output ./output -r win-x86 -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true
        working-directory: ${{ env.AZURE_APP_WORKING_DIR }}

      - name: Test with the dotnet CLI
        run: dotnet test
        working-directory: ${{ env.AZURE_APP_WORKING_DIR }}


      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2  
        with:
          app-name: 'api-contentmgt-dev-001'  
          package: ${{ env.AZURE_APP_WORKING_DIR }}output
          publish-profile: ${{ secrets.API_CONTENTMGT_PUBLISH_PROFILE }}
