name: content-api-build-and-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/apis/ContentManagement/**'
      - '.github/workflows/api-content.yml'
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_APP_WORKING_DIR: './src/apis/ContentManagement/'

jobs:
  api-content-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest  # Keep windows-latest for Windows environment
    environment: Development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3

      - name: Build and Publish
        run: |
          dotnet publish -c Release -o ./output -r win-x86 --self-contained -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true
        working-directory: ${{ env.AZURE_APP_WORKING_DIR }}


      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-contentmgt-dev-001'  
          slot-name: 'production'  # Optional: Specify deployment slot (remove if not using slots)
          package: ${{ env.AZURE_APP_WORKING_DIR }}output
          publish-profile: ${{ secrets.API_CONTENTMGT_PUBLISH_PROFILE }}
