name: API-build & deploy candidate
on:
  push:
    branches:
      - main
    paths:     
      - ".github/workflows/api-candidate.yml"
      - "src/apis/candidate/**"
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./src/apis/candidate/target"
  JAVA_VERSION: "11"
  AZURE_WEBAPP_NAME: "api-candidate-dev-002"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./src/apis/candidate"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.5.3

      - name: "Set up Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: "Build Java App with Maven"
        run: mvn clean package
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/target/*.jar"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.API_CANDIDATE_PUBLISH_PROFILE }}
          package: "*.jar"
