trigger:
  branches:
    include:
      - main # Change this to the branch you want to trigger the CI/CD pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  functionName: 'api-candidate-dev-001'
  artifactName: 'candidate-api'
  publishProfileSecret: ${{secret.API_CANDIDATE_PUBLISH_PROFILE}} # Name of the secret containing the .publishsettings content

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'your-subscription-id' # This field is required, but its value doesn't matter when using Publish Profile.
    appType: 'functionApp'
    appName: 'your-function-app-name' # This field is required, but its value doesn't matter when using Publish Profile.
    package: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
    publishProfile: '$(publishProfileSecret)' # Use the secret containing .publishsettings content
