name: ccadmin-ui-build and deploy  

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'src/client/admin/app/**'
      - '.github/workflows/ui-ccadmin.yml'

env:
  APP_BASE_DIR: 'src/client/admin/app'  
  NODE_VERSION: '16'
  APP_OUTPUT_DIR: 'src/client/admin/app/dist'  
  VITE_APP_API_TENANT_URL: https://api-tenant-dev-001.azurewebsites.net/api
  VITE_APP_API_MICROSITE_URL: https://api-ccmicrosite-dev-001.azurewebsites.net/api
  VITE_APP_API_CANDIDATE_URL: https://api-candidate-dev-002.azurewebsites.net
jobs:
  build-dev:
    if: ${{ github.ref == 'refs/heads/develop' }}  
    runs-on: ubuntu-latest
    environment: Development
    env:
      VITE_APP_HOST: ''
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2 

      - name: Setup Node
        uses: actions/setup-node@v2 
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install packages'
        run: npm ci
        working-directory: ${{ env.APP_BASE_DIR }}
        
      - name: 'Build library'
        run: npm run build
        working-directory: ${{ env.APP_BASE_DIR }}
        
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.CC_AZURE_WEBAPP_PUBLISH_PROFILE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ env.APP_OUTPUT_DIR }}
          api_location: ''
          output_location: ''
          skip_app_build: true
          routes_location: ${{ env.APP_BASE_DIR }}
  build-prd:
    if: ${{ github.ref == 'refs/heads/master' }}  
    runs-on: ubuntu-latest
    environment: Production
    env:
      VITE_APP_HOST: ''
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2 

      - name: Setup Node
        uses: actions/setup-node@v2 
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install packages'
        run: npm ci
        working-directory: ${{ env.APP_BASE_DIR }}
        
      - name: 'Build library'
        run: npm run build
        working-directory: ${{ env.APP_BASE_DIR }}
        
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.CC_UI_ADMIN_PRD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ env.APP_OUTPUT_DIR }}
          api_location: ''
          output_location: ''
          skip_app_build: true
          routes_location: ${{ env.APP_BASE_DIR }}
          